### ISSUE TITLE
opcua field of opcua config.yaml not used, can be removed

### ISSUE THREAD

**Issue by gy95** [kubeedge/mappers-go#40]
`opcua` field of `opcua config.yaml` not used, can be removed
```
mqtt:
  server: tcp://127.0.0.1:1883
  username: ""
  password: ""
  certificationFile: ""
  privateKeyFile: ""
configmap: /opt/kubeedge/deviceProfile.json
opcua:                                              ----------------------not used, can be deleted
  username: ""
  password: ""
  certificationFile: ""
  privateKeyFile: ""
  remoteCertificationFile: ""
```
